### ISSUE TITLE
Please add 'errors' parameter to py2_encode and py2_decode

### ISSUE THREAD

**Issue by fape** [romanvm/kodi.six#1]
The original encode and decode have another optional input parameter, called `errors`
`.encode([encoding], [errors='strict'])` and `.decode([encoding], [errors])`

**Comment by romanvm** [comment]
Normally, you don't need to use those parameters except for specific edge cases of fubared data.

**Comment by romanvm** [comment]
On second thought this might be useful in some scenarios. I'm going to implement this in the future release.

**Comment by fape** [comment]
Thanks.
