### ISSUE TITLE
Syntax error on Kodi 16

### ISSUE THREAD

**Issue by elgatito** [romanvm/kodi.six#5]
Hello,

I was trying to use your library for migrating to Python3.
One of the users reported an error on Kodi 16:

```
                                            SyntaxError: ('invalid syntax', ('/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/.../resources/site-packages/kodi_six/utils.py', 60, 52, '            mod_kwargs = {key: py2_encode(value) for key, value\n'))
```

Kodi 16 is too old for this?

**Comment by romanvm** [comment]
> Kodi 16 is too old for this?

You could say so. It used Python 2.6 on some platforms including Android. And Python 2.6 does not have dictionary comprehensions.

**Comment by elgatito** [comment]
Personally I do not use Kodi 16, but many people use forks of Kodi, which are based on Kodi 16 (mostly on old android devices).

**Comment by romanvm** [comment]
I understand but I don't like the idea of supporting Python 2.6 at all.

**Comment by romanvm** [comment]
Fixed in `gotham` branch. I'll submit it soon.
