### ISSUE TITLE
i got an error updating...

### ISSUE THREAD

**Issue by p060477** [romanvm/kodi.six#8]
pls see this:
https://github.com/Sandmann79/xbmc/issues/551

i've kodi 17.3 portable and trying to update some add on i get errors:

16:53:18.219 T:4164 ERROR: ADDON: extension '' is not currently supported for service addon
16:53:57.014 T:4164 ERROR: Previous line repeats 7 times.
16:53:57.014 T:4164 ERROR: XFILE::CDirectory::GetDirectory - Error getting zip://special%3a%2f%2fhome%2faddons%2fpackages%2fscript.module.six-1.14.0%2bmatrix.2.zip/
16:53:57.014 T:4164 ERROR: CAddonInstallJob[script.module.six]: invalid package special://home/addons/packages/script.module.six-1.14.0+matrix.2.zip
16:53:57.074 T:4164 ERROR: ADDON: extension '' is not currently supported for service addon

how to solve..??
pls guide me as i was a little child cause i'm really not skilled..
thxs so much in adv
cheers

**Comment by romanvm** [comment]
I have no idea why Kodi 17 tries to install "matrix" version of kodi-six.

**Comment by p060477** [comment]
here it is a screen shoot..:

![screenshot000](https://user-images.githubusercontent.com/12773559/112537211-b5de4200-8dae-11eb-9869-f8a0a0f9070a.jpg)

**Comment by romanvm** [comment]
The screenshot does not help much. As I said, I have no idea why Kodi 17 installs "matrix" addons. I have strong suspicion that your Kodi installation is seriously corrupted. Try to install everything from scratch.

**Comment by p060477** [comment]
..i 've a -portable- vers cause i do not want to install so much sw on pc..portable for me is very better and easy and usefull...
maybe should be due to the new pyton 3.0 and kodi 19 add on problems..cause if i downgrade the 5 add ons in the screen shoot i've no problem..but when i try to get the update i've the log error posted here..

**Comment by romanvm** [comment]
Closed as outdated
